services:
  postgres:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vendas
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports: 
    - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql- postgres_data

volumes:
  mysql_data: 
